import type { SchemaGraphKernel } from '../core/create-schema-graph-kernel.js';
import type { Property } from '@atomos/structura-core';

const mapSqlType = (dataType: string): string => {
  switch (dataType) {
    case 'integer': return 'INTEGER';
    case 'float':   return 'DECIMAL(18,6)';
    case 'number':  return 'NUMERIC';
    case 'boolean': return 'BOOLEAN';
    case 'date':    return 'DATE';
    default:        return 'TEXT';
  }
};

export const createSqlAdapter = (kernel: SchemaGraphKernel) => {
  return Object.freeze({
    generateDDL: (): string => {
      const { entities, links } = kernel.getSnapshot();
      const lines: string[] = [
        '-- Auto-generated by atomos-structura',
        '',
      ];

      Object.values(entities).forEach(entity => {
        const tableName = entity.name.replace(/([A-Z])/g, '_$1').replace(/^_/, '').toLowerCase();
        lines.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);
        const cols: string[] = [];

        const hasId = entity.properties.some(p => p.key === 'id');
        if (!hasId) {
          cols.push('  id UUID PRIMARY KEY DEFAULT gen_random_uuid()');
        }

        entity.properties.forEach((prop: Property) => {
          const sqlType = mapSqlType(prop.dataType);
          const notNull = prop.validation?.required ? ' NOT NULL' : '';
          const pk = prop.key === 'id' ? ' PRIMARY KEY DEFAULT gen_random_uuid()' : '';
          cols.push(`  ${prop.key} ${sqlType}${pk}${notNull}`);
        });

        lines.push(cols.join(',\n'), `);\n`);
      });

      // Foreign keys / pivot tables for links
      Object.values(links).forEach(link => {
        const left = entities[link.leftEntityId];
        const right = entities[link.rightEntityId];
        if (!left || !right) return;

        const leftTable = left.name.replace(/([A-Z])/g, '_$1').replace(/^_/, '').toLowerCase();
        const rightTable = right.name.replace(/([A-Z])/g, '_$1').replace(/^_/, '').toLowerCase();

        const isLeftMany = link.leftCardinality === '*' || link.leftCardinality === '1..*';
        const isRightMany = link.rightCardinality === '*' || link.rightCardinality === '1..*';

        if (isLeftMany && isRightMany) {
          // Many-to-many: pivot table
          const pivot = `${leftTable}_${rightTable}`;
          lines.push(
            `CREATE TABLE IF NOT EXISTS ${pivot} (`,
            `  ${leftTable}_id UUID REFERENCES ${leftTable}(id) ON DELETE CASCADE,`,
            `  ${rightTable}_id UUID REFERENCES ${rightTable}(id) ON DELETE CASCADE,`,
            `  PRIMARY KEY (${leftTable}_id, ${rightTable}_id)`,
            `);\n`,
          );
        } else {
          // FK on the "many" side
          const fkTable = isRightMany ? rightTable : leftTable;
          const refTable = isRightMany ? leftTable : rightTable;
          lines.push(
            `ALTER TABLE ${fkTable}`,
            `  ADD COLUMN IF NOT EXISTS ${refTable}_id UUID,`,
            `  ADD CONSTRAINT fk_${fkTable}_${refTable}`,
            `    FOREIGN KEY (${refTable}_id) REFERENCES ${refTable}(id) ON DELETE SET NULL;\n`,
          );
        }
      });

      return lines.join('\n');
    },
  });
};
