import type { Entity } from '../../types/entity.types.js';
import type { LinkProps } from '../../types/link.types.js';

export const generateKubernetesManifests = (
  entities: readonly Entity[],
  _links: readonly LinkProps[]
): string => {
  let yaml = `# Auto-generated by Atomo Structura — Sovereign Kubernetes Manifest Generator\n---\n`;

  const sanitizeK8s = (name: string) => name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const services = entities.filter(e => (e as any).nodeType !== 'zone' && !(e as any).metadata?.isZone && (e as any).nodeType !== 'sticky-note');

  services.forEach(s => {
    const appName = sanitizeK8s(s.name);
    yaml += `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appName}-deployment
  labels:
    app: ${appName}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${appName}
  template:
    metadata:
      labels:
        app: ${appName}
    spec:
      containers:
      - name: ${appName}
        image: ${appName}:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ${appName}-service
spec:
  type: ClusterIP
  selector:
    app: ${appName}
  ports:
  - port: 80
    targetPort: 8080
---
`;
  });

  return yaml;
};

export const generateDockerCompose = (
  entities: readonly Entity[],
  links: readonly LinkProps[]
): string => {
  let yaml = `version: '3.8'\n\nservices:\n`;
  const sanitize = (name: string) => name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  const services = entities.filter(e => (e as any).nodeType !== 'zone' && !(e as any).metadata?.isZone && (e as any).nodeType !== 'sticky-note');

  const dependsMap = new Map<string, string[]>();
  links.forEach(l => {
    if (!dependsMap.has(l.leftEntityId)) dependsMap.set(l.leftEntityId, []);
    dependsMap.get(l.leftEntityId)!.push(l.rightEntityId);
  });

  const entityMap = new Map<string, Entity>(entities.map(e => [e.id, e]));

  services.forEach((s, idx) => {
    const sName = sanitize(s.name);
    yaml += `  ${sName}:\n`;
    yaml += `    image: ${sName}:latest\n`;
    yaml += `    restart: unless-stopped\n`;
    yaml += `    ports:\n`;
    yaml += `      - "${8080 + idx}:8080"\n`;

    const deps = dependsMap.get(s.id) || [];
    if (deps.length > 0) {
      yaml += `    depends_on:\n`;
      deps.forEach(targetId => {
        const target = entityMap.get(targetId);
        if (target) {
          yaml += `      - ${sanitize(target.name)}\n`;
        }
      });
    }
    yaml += `\n`;
  });

  yaml += `networks:\n  default:\n    driver: bridge\n`;
  return yaml;
};
