import type { Entity } from '../../types/entity.types.js';
import type { LinkProps } from '../../types/link.types.js';

/**
 * Converts visual architecture zones and nodes into valid Terraform HCL (AWS provider).
 */
export const generateTerraformHCL = (
  entities: readonly Entity[],
  links: readonly LinkProps[]
): string => {
  let hcl = `# Auto-generated by Atomo Structura — Sovereign Terraform Generator
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

`;

  const sanitize = (name: string) => name.toLowerCase().replace(/[^a-z0-9_]/g, '_');

  // 1. VPC & Subnet Zones
  const zones = entities.filter(e => (e as any).nodeType === 'zone' || (e as any).metadata?.isZone);
  zones.forEach((z, idx) => {
    const resName = sanitize(z.name || `vpc_${idx}`);
    const bType = ((z as any).boundaryType || 'vpc').toLowerCase();

    if (bType === 'subnet') {
      hcl += `resource "aws_subnet" "${resName}" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.${idx + 1}.0/24"
  availability_zone = "\${var.aws_region}a"

  tags = {
    Name = "${z.name}"
  }
}

`;
    } else {
      hcl += `resource "aws_vpc" "${resName}" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "${z.name}"
  }
}

`;
    }
  });

  // 2. Standard Service Nodes (EC2, RDS, S3, Lambda)
  const services = entities.filter(e => (e as any).nodeType !== 'zone' && !(e as any).metadata?.isZone && (e as any).nodeType !== 'sticky-note');

  services.forEach(s => {
    const resName = sanitize(s.name);
    const lower = s.name.toLowerCase();

    if (lower.includes('db') || lower.includes('database') || lower.includes('postgres') || lower.includes('mysql') || s.nodeType === 'cylinder') {
      hcl += `resource "aws_db_instance" "${resName}" {
  identifier          = "${resName.replace(/_/g, '-')}"
  allocated_storage   = 20
  engine              = "postgres"
  engine_version      = "16.1"
  instance_class      = "db.t4g.micro"
  username            = "dbadmin"
  manage_master_user_password = true
  skip_final_snapshot = true

  tags = {
    Name = "${s.name}"
  }
}

`;
    } else if (lower.includes('s3') || lower.includes('bucket') || lower.includes('storage')) {
      hcl += `resource "aws_s3_bucket" "${resName}" {
  bucket = "${resName.replace(/_/g, '-')}-\${var.aws_region}"

  tags = {
    Name = "${s.name}"
  }
}

`;
    } else if (lower.includes('lambda') || lower.includes('function') || lower.includes('worker')) {
      hcl += `resource "aws_lambda_function" "${resName}" {
  function_name = "${resName}"
  role          = aws_iam_role.lambda_exec.arn
  handler       = "index.handler"
  runtime       = "nodejs20.x"

  tags = {
    Name = "${s.name}"
  }
}

`;
    } else {
      // Default EC2 / ECS Service
      hcl += `resource "aws_instance" "${resName}" {
  ami           = "ami-0c7217cdde317cfec" # Amazon Linux 2023
  instance_type = "t3.micro"

  tags = {
    Name = "${s.name}"
  }
}

`;
    }
  });

  return hcl;
};
